### PR TITLE
Add Dockerfile for development purposes

### PR DESCRIPTION
**Pull request by jremes-ho**
Hi.

It looks like this repository was missing a Dockerfile for development purposes. I have added one, based on Alpine 3.18 NodeJS 20 version to make it light-weight. 

Usage of Dockerfile is fully documented in README.md file, I have taken precautions not to run the container as root and Dockerfile is fully tested in my local machine.

Thanks.

### CODE REVIEW

**Review by chrisns — APPROVED** [review]
you could if you like add a `dockerignore` to prevent unnecessary files like the `.github` directory getting in the image, but its not going anywhere so 👍

**Comment by jremes-ho** [comment]
Please review further changes I've made, including dockerignore file. Thanks.

**Review by chrisns — APPROVED** [review]

**Comment by chrisns** [comment]
🚀👍 not that my review means anything, i've not got write access :(

**Comment by sdh100shaun** [comment]
thanks for the contribution

**Review by sdh100shaun — APPROVED** [review]

**Comment by jremes-ho** [comment]
Please merge, I do not have write access to repository. Thanks.

**Comment by heathd** [comment]
tested, works great, thanks!

**Pull request merged**
