### PR TITLE
x-gov open source may 2023 community notes 

### PR DESCRIPTION
**Pull request by asmith-nhsx**

### CODE REVIEW

**Review by reggieb — APPROVED** [review]
Looks good to me

**Review by RobNicholsGDS — APPROVED** [review]
LGTM

**Comment by heathd** [comment]
@asmith-nhsx happy to merge.. do you have the presentation available in any other format (eg. PDF or PPT) as the pngs are not going to be accessible for screen reader users

**Review by heathd — APPROVED** [review]

**Review by sdh100shaun — APPROVED** [review]

**Comment by sdh100shaun** [comment]
> @asmith-nhsx happy to merge.. do you have the presentation available in any other format (eg. PDF or PPT) as the pngs are not going to be accessible for screen reader users

Agree - but have merged

**Comment by asmith-nhsx** [comment]
Thanks, yes I have asked the speaker to provide them in md format, but that will take time. Thanks for approving in the meantime

**Pull request merged**
